name: First Workflow
on: push # при пуші в гілку main

jobs: # джоба виконує команди
  run-first-command: # назва джоби
    runs-on: ubuntu-latest # визначає систему, на якій буде виконуватися джоба
    steps: # кроки, які будуть виконуватися в джобі
      - name: Display some Text # назва кроку
        run: echo "Some Text" # команда, яка буде виконуватися в кроці
      - name: Command in Multiline # назва кроку
        run: | # команда, яка буде виконуватися в кроці
          node -v
          npm -v
        