name: Fourth Workflow
on:
  workflow_run: # вказуємо, що цей workflow буде запускатися після виконання іншого workflow
    workflows: ["Third Workflow"] # вказуємо, що цей workflow буде запускатися після виконання "Third Workflow"
    types:
      - completed # вказуємо, що цей workflow буде запускатися після завершення "Third Workflow"

jobs:
  success-command:
    runs-on: ubuntu-latest
    # вказуємо, що ця джоба буде виконуватися тільки якщо "Third Workflow" завершився успішно
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        run: echo "Success"
  failure-command:
    runs-on: ubuntu-latest
    # вказуємо, що ця джоба буде виконуватися тільки якщо "Third Workflow" завершився з помилкою
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
        run: echo "Faild"