name: Third Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Command in Multiline
        run: | # "|"команда, яка буде виконуватися в кроці (виконує кілька рядків)
          pwd # команда для відображення поточного робочого каталогу
          ls -a # команда для відображення всіх файлів та папок у поточному робочому каталозі
          
